import os
os.system("sudo apt update")
os.system("sudo apt -y upgrade")
os.system("python3 -V")
os.system("sudo apt install -y python3-pip")
os.system("pip install numpy")
os.system("pip install python-binance")
# os.system("pip install tensorflow")
# os.system("pip install pandas")
os.system("pip install -U scikit-learn")
os.system("pip install scipy")
os.system("pip install numba")
os.system("pip install psutil")
os.system("chmod +x arun.sh")
os.system("chmod +x akill.sh")

